version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo "Building the Training Docker image..."
      - cd $CODEBUILD_SRC_DIR/$DOCKERFILE_PATH 
      - REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - |
        if docker pull $REPO:$IMAGE_TAG; then
            docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG --cache-from $REPO:$IMAGE_TAG .
        else
            docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
        fi
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPO:$IMAGE_TAG      
      - echo "Pushing the Docker image..."
      - docker push $REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`




